### ISSUE TITLE
The wasmer API rewrite

### ISSUE THREAD

**Issue by floren** [vedhavyas/wasm#7]
As far as I can tell, this is still the only possibility for running WASM code compiled with the Go toolchain--at least, it's where the wasmer people point anyone who asks about it. However, this is written using the previous version of the wasmer API. I've taken a few pokes at updating it to use the current API, but I just don't understand wasmer well enough to do the job right now.

What's the plan for the future? Is an update in the works? Apologies for what is perhaps a vague issue.

**Comment by Hywan** [comment]
Updating to Wasmer 1.0 should not be that difficult. Host functions are now regular Go functions, `cgo` is no longer required.

For example: https://github.com/go-wasm-adapter/go-wasm/blob/8b546c20748035ed5f60a0f53db261240a38b322/imports.go#L43-L46

should be rewritten:

```go
func debug(sp int32) {
	log.Println(sp)
}
```

That's it. And `addImports` should return a `wasmer.ImportObject`.

**Comment by floren** [comment]
What about the other functions, which modify memory? For instance:

```
//export wexit
func wexit(ctx unsafe.Pointer, sp int32) {
	b := getBridge(ctx)
	b.exitCode = int(b.getUint32(sp + 8))
	b.cancF()
}

//export wwrite
func wwrite(ctx unsafe.Pointer, sp int32) {
	b := getBridge(ctx)
	fd := int(b.getInt64(sp + 8))
	p := int(b.getInt64(sp + 16))
	l := int(b.getInt32(sp + 24))
	_, err := syscall.Write(fd, b.mem()[p:p+l])
	if err != nil {
		panic(fmt.Errorf("wasm-write: %v", err))
	}
}
```

In the old API, ctx let us find the Bridge object, which could in turn access memory as needed for getInt64, etc. 

As I understand the new API, it looks like we would access memory through a wasmer.Instance object's Exports field, but when we're inside a function (e.g. `func wexit(sp int32)`) how do we *get* this Instance? You can't just have a global if you hope to run more than one WASM program at a time. I suppose you could pass the wasmer.Instance to the `addImports` function and define all the exported Go functions as lambdas *inside* addImports, so they can capture the Instance?

**Comment by Hywan** [comment]
It's possible to add a host function with a custom user-defined environment, and then add a reference to the instance's memory inside this environment. See https://github.com/wasmerio/wasmer-go/issues/173#issuecomment-777464575 to learn how to get the current `Instance` inside a host function. From the `Instance`, you can get the memory, or you can directly reference the `Memory` inside the environment.

**Comment by floren** [comment]
Thanks, Hywan, this has been a big help. I've got a crude update, full of debug prints and such, in https://github.com/floren/go-wasm/tree/go1.15

I added a new example that just prints "hello, world" in the wasm program's main. I've been able to get it to actually run and print to the console, but then something is panicking:

```
% ./hello-caller 
2021/03/03 09:52:57 BridgeFromBytes begins
2021/03/03 09:52:57 imports added
2021/03/03 09:52:57 NewInstanceWithImports done
hello, world
fatal error: exitsyscall: syscall frame is no longer valid

goroutine 1 [running, locked to thread]:
runtime.throw(0x5aaf25, 0x2d)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000169cd0 sp=0xc000169ca0 pc=0x43c932
runtime.exitsyscall()
	/usr/local/go/src/runtime/proc.go:3225 +0x22a fp=0xc000169d00 sp=0xc000169cd0 pc=0x46be4a
runtime.cgocall(0x555180, 0xc000169d68, 0xc000012e10)
	/usr/local/go/src/runtime/cgocall.go:152 +0x9e fp=0xc000169d38 sp=0xc000169d00 pc=0x40b39e
github.com/wasmerio/wasmer-go/wasmer._Cfunc_wasm_func_call(0x7fa9048fe070, 0xc000012e20, 0xc000012e10, 0x7fa90789aa40)
	_cgo_gotypes.go:1216 +0x4e fp=0xc000169d68 sp=0xc000169d38 pc=0x54302e
github.com/wasmerio/wasmer-go/wasmer.(*Function).Native.func1.5(0xc00010b7d0, 0xc000012e20, 0xc000012e10, 0x2)
	/home/john/go/pkg/mod/github.com/wasmerio/wasmer-go@v1.0.3/wasmer/function.go:317 +0xd1 fp=0xc000169da0 sp=0xc000169d68 pc=0x54a3b1
github.com/wasmerio/wasmer-go/wasmer.(*Function).Native.func1(0xc00000eac0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/home/john/go/pkg/mod/github.com/wasmerio/wasmer-go@v1.0.3/wasmer/function.go:317 +0x3ff fp=0xc000169f30 sp=0xc000169da0 pc=0x54a7df
main.main()
	/home/john/hacking/go-wasm/examples/hello-caller/main.go:23 +0xfa fp=0xc000169f88 sp=0xc000169f30 pc=0x554ada
runtime.main()
	/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc000169fe0 sp=0xc000169f88 pc=0x43f129
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000169fe8 sp=0xc000169fe0 pc=0x46fec1
```

Debugging this with delve has proved... challenging, so if you have any insight, I'd appreciate it. Note that I'm taking the absolute simplest approach: I call instance.Exports.GetFunction("run"), then execute the results: `run(0, 0)`.

**Comment by floren** [comment]
Question retracted, figured it out, apologies for the noise.

**Comment by Hywan** [comment]
Why closing the issue? I would be happy to help to update this project. Are you going to submit your patch as a PR?
